services:
  rdbms-async-innodb-reload-server:
    build:
      context: ./async-innodb-reload
      dockerfile: ../Dockerfile.rdbms-async-innodb-reload
      args:
        - RUST_BIN_NAME=${RUST_BIN_NAME}
        - USER=${SERVER_USERNAME:-admin}
        - PASS=${SERVER_PASSWORD:-password}
        - RSYNC_USER=rsyncuser
        - LAKEHOUSE_DIR=/lakehouse
        - RDBMS_UID=${RDBMS_UID:-1001}
        - RDBMS_GID=${RDBMS_GID:-1001}
    container_name: rdbms-async-innodb-reload-server
    env_file: .env
    user: "${RDBMS_UID:-1001}:${RDBMS_GID:-1001}"
    volumes:
      - ./lakehouse/s3:/lakehouse
      - ./scripts/svr:/home/${SERVER_USERNAME:-admin}/etl
      - ./entrypoint.d/async-innodb-reload.entrypoint.sh:/entrypoint.sh
      - lakehouse-rsync:/lakehouse/rsync
    networks:
      - rdbms-network
    ports:
      - "2222:22"
      - "50000:50000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  rdbms-rsync-csv:
    build:
      context: ./rsync-csv
      dockerfile: ../Dockerfile.rdbms-rsync-csv
      args:
        - USER=${REMOTE_SSH_USERNAME:-admin}
        - PASS=${REMOTE_SSH_PASSWORD:-password}
        - SOURCE_DIR=${SOURCE_DIR:-/lakehouse}
        - TEMPLATE_DIR=${TEMPLATE_DIR:-/templates}
        - SERVER_PASSWORD=${SERVER_PASSWORD:-password}
        - RDBMS_UID=${RDBMS_UID:-1001}
        - RDBMS_GID=${RDBMS_GID:-1001}
    container_name: rdbms-rsync-csv
    env_file: .env
    user: "${RDBMS_UID:-1001}:${RDBMS_GID:-1001}"
    volumes:
      - ./lakehouse/user/csv_templates:/lakehouse_templates
      - ./lakehouse/user/data_dictionaries:/lakehouse_data_dictionaries
      - ./scripts/user:/home/${SERVER_USERNAME:-admin}/tools
      - ./scripts/user/sync_templates_and_dictionaries.sh:/usr/local/bin/sync_templates_and_dictionaries.sh
      - ./supervisor/rsync-csv.supervisord.conf:/etc/supervisor/supervisord.conf.tpl
      - ./entrypoint.d/rsync-csv.entrypoint.sh:/entrypoint.sh
      - persistent-home:/home
    networks:
      - rdbms-network
    ports:
      - "4444:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - rdbms-async-innodb-reload-server

volumes:
  persistent-home:
  lakehouse-rsync:

networks:
  rdbms-network:
    driver: bridge